name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
#     - uses: actions/checkout@v3
#     - name: Deploy to staging
#       uses: appleboy/ssh-action@master
#       with:
#         username: ${{ secrets.USERNAME_STAGING }}
#         host: ${{ secrets.HOST_STAGING }}
#         password: ${{ secrets.PASSWORD_STAGING }}
#         script: "cd /home/u890410510/domains/integrasiautama.my.id/develop-web-bestive && sh deploy.sh"
